modLoader = "${loader}"
loaderVersion = "${loader_version_range}"
license = "${mod_license}"

[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_name}"
authors = "${mod_authors}"
description = '''${mod_description}'''
# A URL to query for updates for this mod. See the JSON update specification https://docs.neoforged.net/docs/misc/updatechecker/
#updateJSONURL="https://change.me.example.invalid/updates.json" #optional
# A URL for the "homepage" for this mod, displayed in the mod UI
#displayURL="https://change.me.to.your.mods.homepage.example.invalid/" #optional
# A file name (in the root of the mod JAR) containing a logo for display
#logoFile="examplemod.png" #optional
# A text field displayed in the mod UI
#credits="" #optional

enumExtensions = "META-INF/enumextensions.json"

[[dependencies.${ mod_id }]]
modId = "neoforge"
type = "required"
versionRange = "${neo_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.${ mod_id }]]
modId = "minecraft"
type = "required"
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.${ mod_id }]]
modId = "geckolib"
type = "required"
versionRange = "[${geckolib_version},)"
ordering = "NONE"
side = "BOTH"
[dependencies.${ mod_id }.mc-publish]
modrinth = "geckolib"
curseforge = "geckolib"

[[dependencies.${ mod_id }]]
modId = "kotlinforforge"
type = "required"
versionRange = "[${kff_version},)"
ordering = "NONE"
side = "BOTH"
[dependencies.${ mod_id }.mc-publish]
modrinth = "kotlin-for-forge"
curseforge = "kotlin-for-forge"

[[dependencies.${ mod_id }]]
modId = "curios"
type = "optional"
ordering = "NONE"
side = "BOTH"
[dependencies.${ mod_id }.mc-publish]
modrinth = "curios"
curseforge = "curios"

[[dependencies.${ mod_id }]]
modId = "jei"
type = "optional"
ordering = "NONE"
side = "BOTH"
[dependencies.${ mod_id }.mc-publish]
modrinth = "jei"
curseforge = "jei"

[[dependencies.${ mod_id }]]
modId = "emi"
type = "optional"
ordering = "NONE"
side = "BOTH"
[dependencies.${ mod_id }.mc-publish]
modrinth = "emi"
curseforge = "emi"

# Features are specific properties of the game environment, that you may want to declare you require. This example declares
# that your mod requires GL version 3.2 or higher. Other features will be added. They are side aware so declaring this won't
# stop your mod loading on the server for example.
#[features.${mod_id}]
#openGLVersion="[3.2,)"

[[mixins]]
config = "${mod_id}.mixins.json"

[mc-publish]
curseforge = "1271073"
modrinth = "pGCxoM3B"