name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1000
          fetch-tags: true

      - name: Setup JDK
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Build
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build
      - name: Find built asset
        id: find_file
        run: |
          FILE=$(find build/libs -name "*.jar" | head -n 1)
          echo "asset=$FILE" >> $GITHUB_OUTPUT
      - name: Upload jar artifact
        uses: actions/upload-artifact@v4
        with:
          name: Mod Jar
          path: ${{ steps.find_file.outputs.asset }}