name: Release

on:
  release:
    types: [ published ]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Setup JDK
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Build
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build
      - name: Find built asset
        id: find_file
        run: |
          FILE=$(find build/libs -name "*.jar" | head -n 1)
          echo "asset=$FILE" >> $GITHUB_OUTPUT
      - name: Upload jar to Github Release
        uses: softprops/action-gh-release@v2
        with:
          files: ${{ steps.find_file.outputs.asset }}
          make_latest: true
      - name: Release on Curseforge and Modrinth
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          files: ${{ steps.find_file.outputs.asset }}
          version-type: release
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
          curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}